In [1]:
import pandas as pd
from faker import Faker
import random
import numpy as np

In [2]:
fake = Faker()
id = []
name = []
username = []
birthdate = []
job = []
sex = []

In [3]:
fake.profile()

{'job': 'Doctor, hospital',
 'company': 'Robinson, Graham and Thompson',
 'ssn': '029-04-3133',
 'residence': '448 Mary Stream Apt. 122\nEast Toddside, MS 22422',
 'current_location': (Decimal('65.1180345'), Decimal('-166.707825')),
 'blood_group': 'AB+',
 'website': ['http://www.hunt.com/', 'https://www.hunter-crawford.info/'],
 'username': 'maddoxamanda',
 'name': 'Ashley Henry',
 'sex': 'F',
 'address': '9181 Jason Springs Apt. 757\nNorth Danielberg, CO 15884',
 'mail': 'robertsrobert@gmail.com',
 'birthdate': datetime.date(1972, 1, 14)}

In [4]:
fake.date_of_birth(minimum_age = 18)

datetime.date(1931, 2, 4)

In [5]:
for i in range(101):
    id.append(i)
    name.append(fake.profile()['name'])
    username.append(fake.profile()['username'])
    birthdate.append(fake.date_of_birth(minimum_age = 18))
    job.append(fake.profile()['job'])
    sex.append(fake.profile()['sex'])

In [59]:
len(sex)

101

In [6]:
from datetime import date

def calculate_age(born):
    today = date.today()
    return today.year - born.year - ((today.month, today.day) < (born.month, born.day))

In [7]:
calculate_age(birthdate[6])

21

In [8]:
user_data = pd.DataFrame()

In [9]:
user_data['ID'] = id
user_data['name'] = name
user_data['username'] = username
user_data['birthdate'] = birthdate
user_data['job'] = job
user_data['sex'] = sex
user_data

ID              name        username   birthdate  \
0      0     Deborah Olson  jamesrodriguez  1940-05-31   
1      1  Stephanie Taylor        nicole89  1964-02-16   
2      2       Erin Torres   robertsonkyle  2002-10-20   
3      3       James Young        mcarlson  1918-01-26   
4      4   Matthew Wallace         harry61  1990-02-07   
..   ...               ...             ...         ...   
96    96      Wanda Rivera         edgar47  1953-10-29   
97    97        Edgar Page       donnachan  1964-04-19   
98    98     Travis Harper    williamspaul  1929-07-12   
99    99  Kimberly Burgess        jayhicks  1948-04-10   
100  100     Laura Sanders    dominicburns  1947-09-28   

                                job sex  
0    Furniture conservator/restorer   M  
1                Wellsite geologist   F  
2        Geophysical data processor   F  
3               Engineer, materials   F  
4                Editor, film/video   M  
..                              ...  ..  
96               Surveyor, quantity   M  
97         Journalist, broadcasting   M  
98                     Risk manager   F  
99               Surveyor, building   M  
100                    Geoscientist   F  

[101 rows x 6 columns]

In [10]:
user_data.to_csv("user_data.csv", index=False)

In [3]:
user_data = pd.read_csv("user_data.csv")

In [4]:
user_data

ID              name        username   birthdate  \
0      0     Deborah Olson  jamesrodriguez  1940-05-31   
1      1  Stephanie Taylor        nicole89  1964-02-16   
2      2       Erin Torres   robertsonkyle  2002-10-20   
3      3       James Young        mcarlson  1918-01-26   
4      4   Matthew Wallace         harry61  1990-02-07   
..   ...               ...             ...         ...   
96    96      Wanda Rivera         edgar47  1953-10-29   
97    97        Edgar Page       donnachan  1964-04-19   
98    98     Travis Harper    williamspaul  1929-07-12   
99    99  Kimberly Burgess        jayhicks  1948-04-10   
100  100     Laura Sanders    dominicburns  1947-09-28   

                                job sex  
0    Furniture conservator/restorer   M  
1                Wellsite geologist   F  
2        Geophysical data processor   F  
3               Engineer, materials   F  
4                Editor, film/video   M  
..                              ...  ..  
96               Surveyor, quantity   M  
97         Journalist, broadcasting   M  
98                     Risk manager   F  
99               Surveyor, building   M  
100                    Geoscientist   F  

[101 rows x 6 columns]

In [30]:
content_data = pd.read_csv("TVNZ_metadata.csv")
content_data.head()


title  \
0     Watch Absolutely Fabulous S4E7 | TVNZ OnDemand   
1           Watch Amelia Parker S1E4 | TVNZ OnDemand   
2           Watch Amelia Parker S1E8 | TVNZ OnDemand   
3  Watch Aqua Teen Hunger Force S1E2 | TVNZ OnDemand   
4                    Watch Back S1E5 | TVNZ OnDemand   

                                         description  \
0  Patsy goes to New York Fashion Week to find id...   
1  Amelia struggles to communicate with her first...   
2  Amelia learns to set boundaries when Nathan ta...   
3  Leprechauns use Dr. Weird's Rainbow Maker 400 ...   
4  The family set about clearing up after the dis...   

                                               image  \
0  https://play-images-prod-catalog.tech.tvnz.co....   
1  https://play-images-prod-catalog.tech.tvnz.co....   
2  https://play-images-prod-catalog.tech.tvnz.co....   
3  https://play-images-prod-catalog.tech.tvnz.co....   
4  https://play-images-prod-catalog.tech.tvnz.co....   

                                                 url  \
0  https://www.tvnz.co.nz/shows/absolutely-fabulo...   
1  https://www.tvnz.co.nz/shows/amelia-parker/epi...   
2  https://www.tvnz.co.nz/shows/amelia-parker/epi...   
3  https://www.tvnz.co.nz/shows/aqua-teen-hunger-...   
4   https://www.tvnz.co.nz/shows/back/episodes/s1-e5   

                                            keywords category  ID  cluster  
0  genre:comedy,genre:box-set,genre:christmas,moo...   comedy   0        4  
1  genre:family,genre:comedy,genre:closed-caption...   comedy   1        0  
2  genre:family,genre:comedy,genre:closed-caption...   comedy   2        0  
3  genre:box-set,genre:comedy,mood:crack-up,mood:...   comedy   5        0  
4  genre:box-set,genre:comedy,mood:irreverent,moo...   comedy   6        2

In [47]:
content_data['title'] = content_data['title'].str.split("|").str.get(0)
content_data.head()

title  \
0     Watch Absolutely Fabulous S4E7    
1           Watch Amelia Parker S1E4    
2           Watch Amelia Parker S1E8    
3  Watch Aqua Teen Hunger Force S1E2    
4                    Watch Back S1E5    

                                         description  \
0  Patsy goes to New York Fashion Week to find id...   
1  Amelia struggles to communicate with her first...   
2  Amelia learns to set boundaries when Nathan ta...   
3  Leprechauns use Dr. Weird's Rainbow Maker 400 ...   
4  The family set about clearing up after the dis...   

                                               image  \
0  https://play-images-prod-catalog.tech.tvnz.co....   
1  https://play-images-prod-catalog.tech.tvnz.co....   
2  https://play-images-prod-catalog.tech.tvnz.co....   
3  https://play-images-prod-catalog.tech.tvnz.co....   
4  https://play-images-prod-catalog.tech.tvnz.co....   

                                                 url  \
0  https://www.tvnz.co.nz/shows/absolutely-fabulo...   
1  https://www.tvnz.co.nz/shows/amelia-parker/epi...   
2  https://www.tvnz.co.nz/shows/amelia-parker/epi...   
3  https://www.tvnz.co.nz/shows/aqua-teen-hunger-...   
4   https://www.tvnz.co.nz/shows/back/episodes/s1-e5   

                                            keywords category  ID  cluster  
0  genre:comedy,genre:box-set,genre:christmas,moo...   comedy   0        4  
1  genre:family,genre:comedy,genre:closed-caption...   comedy   1        0  
2  genre:family,genre:comedy,genre:closed-caption...   comedy   2        0  
3  genre:box-set,genre:comedy,mood:crack-up,mood:...   comedy   5        0  
4  genre:box-set,genre:comedy,mood:irreverent,moo...   comedy   6        2

In [48]:
content_data.to_csv("TVNZ_metadata.csv", index=False)

In [50]:
def Jaccard_Similarity(doc1, doc2): 
    
    # List the unique words in a document
    words_doc1 = set(doc1.lower().split()) 
    words_doc2 = set(doc2.lower().split())
    
    # Find the intersection of words list of doc1 & doc2
    intersection = words_doc1.intersection(words_doc2)

    # Find the union of words list of doc1 & doc2
    union = words_doc1.union(words_doc2)
        
    # Calculate Jaccard similarity score 
    # using length of intersection set divided by length of union set
    return float(len(intersection)) / len(union)

main_title = content_data['title'][1]

In [54]:
Jaccard_Similarity(main_title, content_data['title'][1])

1.0

In [55]:
similarity = []

for title in content_data['title']:
    similarity.append(Jaccard_Similarity(main_title, title))

In [66]:
jac = pd.DataFrame(similarity, columns=['distance'])
jac.sort_values(by=['distance'], ascending=False)[1:6].index

Int64Index([2, 12271, 14562, 9956, 2368], dtype='int64')

In [22]:
content_data['k_means'].value_counts()

2    44
3    31
1    21
4    20
5    14
6    14
0     8
Name: k_means, dtype: int64

In [41]:
# rating = []
# comment = []
# user_id = []
# content_id = []

# for _ in range(100):
#     rating.append(random.randint(1,5))
#     comment.append(fake.paragraph(nb_sentences = 10))
#     user_id.append(random.randint(0, max(user_data.ID)))
#     content_id.append(random.randint(0, max(content_data.ID)))

In [55]:
like, dislike = random.sample(range(1, max(content_data['k_means'])), 2)

In [57]:
dislike

2

In [14]:
rating = []
comment = []
user_id = []
content_id = []

for j in range(max(user_data['ID']+1)):
    like, dislike = random.sample(range(1, max(content_data['cluster'])), 2)
    sample_movie = content_data.sample(frac=0.1).reset_index()
    for movie in range(len(sample_movie)):
        if sample_movie['cluster'].iloc[movie] == like:
            rating.append(random.randint(1,5))
            comment.append(fake.paragraph(nb_sentences = 10))
            user_id.append(j)
            content_id.append(sample_movie['ID'].iloc[movie])
        if sample_movie['cluster'].iloc[movie] == dislike:
            rating.append(random.randint(-5,-1))
            comment.append(fake.paragraph(nb_sentences = 10))
            user_id.append(j)
            content_id.append(sample_movie['ID'].iloc[movie])

In [15]:
rating_data = pd.DataFrame()
rating_data['rating'] = rating
rating_data['comment'] = comment
rating_data['user_id'] = user_id
rating_data['content_id'] = content_id
rating_data

rating                                            comment  user_id  \
0          -2  Magazine deal fire glass production. Nature be...        0   
1           4  Indeed end director whom leave. Relate approac...        0   
2           3  Mr special executive money. Better employee ca...        0   
3           5  Stage television short. Pick across way build ...        0   
4          -5  Ago call early. Man not fish majority address....        0   
...       ...                                                ...      ...   
11073      -4  Manage field serve but outside. Behavior raise...      100   
11074      -1  Herself more nothing beautiful you. Inside fal...      100   
11075      -1  Easy all main specific after. Civil fact budge...      100   
11076       3  Street white million officer go movie new. Cur...      100   
11077       5  Writer major various left by. Race indeed assu...      100   

       content_id  
0            8822  
1            5388  
2            6173  
3            9956  
4            8787  
...           ...  
11073       13721  
11074       15559  
11075       13706  
11076        8436  
11077        8464  

[11078 rows x 4 columns]

In [16]:
rating_data.to_csv("rating_data.csv", index=False)

In [79]:
# rating_data.groupby(['user_id', 'content_id']).max('rating')

rating
user_id content_id        
0       6               -1
        8               -2
        10              -3
        50              -1
        65              -4
...                    ...
99      86               1
        88               4
        101             -3
        131             -4
        147              3

[861 rows x 1 columns]

In [17]:
rating_data.pivot(index='content_id', columns='user_id', values='rating').fillna(0)

user_id     0    1    2    3    4    5    6    7    8    9    ...  91   92   \
content_id                                                    ...             
0           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
6           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
7           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
13          0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
17          0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...         ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
16614       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 -4.0  0.0  ...  0.0  0.0   
16615       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
16616       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
16618       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
16622       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   

user_id     93   94   95   96   97   98   99   100  
content_id                                          
0           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
6           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
7           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
13         -3.0  0.0  2.0  0.0  0.0  0.0  0.0  0.0  
17          0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...         ...  ...  ...  ...  ...  ...  ...  ...  
16614       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
16615       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
16616       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
16618       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
16622       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5271 rows x 101 columns]

In [16]:
rating_data.to_csv("rating_data.csv", index=False)

In [18]:
combine = content_data.merge(rating_data.merge(user_data, left_on=['user_id'], right_on=['ID']), left_on=['ID'], right_on=['content_id'] )

In [21]:
combine = combine.drop(columns=['ID_x', 'ID_y'])

KeyError: "['ID_x', 'ID_y'] not found in axis"

In [22]:
combine

title  \
0         Watch Absolutely Fabulous S4E7 | TVNZ OnDemand   
1         Watch Absolutely Fabulous S4E7 | TVNZ OnDemand   
2         Watch Absolutely Fabulous S4E7 | TVNZ OnDemand   
3                        Watch Back S1E5 | TVNZ OnDemand   
4                        Watch Back S1E5 | TVNZ OnDemand   
...                                                  ...   
11073  Watch Who Killed Lucy The Poodle? S1E2 | TVNZ ...   
11074  Watch Who Killed Lucy The Poodle? S1E4 | TVNZ ...   
11075  Watch Who Killed Lucy The Poodle? S1E4 | TVNZ ...   
11076  Watch Who Killed Lucy The Poodle? | Full Seaso...   
11077  Watch Who Killed Lucy The Poodle? | Full Seaso...   

                                             description  \
0      Patsy goes to New York Fashion Week to find id...   
1      Patsy goes to New York Fashion Week to find id...   
2      Patsy goes to New York Fashion Week to find id...   
3      The family set about clearing up after the dis...   
4      The family set about clearing up after the dis...   
...                                                  ...   
11073  A trip to Rotorua to search the archives revea...   
11074  Hitting dead ends and unable to contact key wi...   
11075  Hitting dead ends and unable to contact key wi...   
11076  The survivor of a disastrous circus event in t...   
11077  The survivor of a disastrous circus event in t...   

                                                   image  \
0      https://play-images-prod-catalog.tech.tvnz.co....   
1      https://play-images-prod-catalog.tech.tvnz.co....   
2      https://play-images-prod-catalog.tech.tvnz.co....   
3      https://play-images-prod-catalog.tech.tvnz.co....   
4      https://play-images-prod-catalog.tech.tvnz.co....   
...                                                  ...   
11073  https://play-images-prod-catalog.tech.tvnz.co....   
11074  https://play-images-prod-catalog.tech.tvnz.co....   
11075  https://play-images-prod-catalog.tech.tvnz.co....   
11076  https://play-images-prod-ctf.tech.tvnz.co.nz/a...   
11077  https://play-images-prod-ctf.tech.tvnz.co.nz/a...   

                                                     url  \
0      https://www.tvnz.co.nz/shows/absolutely-fabulo...   
1      https://www.tvnz.co.nz/shows/absolutely-fabulo...   
2      https://www.tvnz.co.nz/shows/absolutely-fabulo...   
3       https://www.tvnz.co.nz/shows/back/episodes/s1-e5   
4       https://www.tvnz.co.nz/shows/back/episodes/s1-e5   
...                                                  ...   
11073  https://www.tvnz.co.nz/shows/who-killed-lucy-t...   
11074  https://www.tvnz.co.nz/shows/who-killed-lucy-t...   
11075  https://www.tvnz.co.nz/shows/who-killed-lucy-t...   
11076  https://www.tvnz.co.nz/shows/who-killed-lucy-t...   
11077  https://www.tvnz.co.nz/shows/who-killed-lucy-t...   

                                                keywords    category  cluster  \
0      genre:comedy,genre:box-set,genre:christmas,moo...      comedy        4   
1      genre:comedy,genre:box-set,genre:christmas,moo...      comedy        4   
2      genre:comedy,genre:box-set,genre:christmas,moo...      comedy        4   
3      genre:box-set,genre:comedy,mood:irreverent,moo...      comedy        2   
4      genre:box-set,genre:comedy,mood:irreverent,moo...      comedy        2   
...                                                  ...         ...      ...   
11073  genre:documentary,genre:new-zealand,genre:box-...  true-crime        4   
11074  genre:documentary,genre:new-zealand,genre:box-...  true-crime        4   
11075  genre:documentary,genre:new-zealand,genre:box-...  true-crime        4   
11076  genre:documentary,genre:new-zealand,genre:box-...  true-crime       12   
11077  genre:documentary,genre:new-zealand,genre:box-...  true-crime       12   

       rating                                            comment  user_id  \
0           4  Answer find car he although hot bank. Somebody...       28   
1           3  Amount floor concern open

In [23]:
combine.to_csv('combine.csv', index=False)

In [2]:
combine = pd.read_csv('combine.csv')

In [19]:
combine

title  \
0         Watch Absolutely Fabulous S4E7 | TVNZ OnDemand   
1         Watch Absolutely Fabulous S4E7 | TVNZ OnDemand   
2         Watch Absolutely Fabulous S4E7 | TVNZ OnDemand   
3                        Watch Back S1E5 | TVNZ OnDemand   
4                        Watch Back S1E5 | TVNZ OnDemand   
...                                                  ...   
11073  Watch Who Killed Lucy The Poodle? S1E2 | TVNZ ...   
11074  Watch Who Killed Lucy The Poodle? S1E4 | TVNZ ...   
11075  Watch Who Killed Lucy The Poodle? S1E4 | TVNZ ...   
11076  Watch Who Killed Lucy The Poodle? | Full Seaso...   
11077  Watch Who Killed Lucy The Poodle? | Full Seaso...   

                                             description  \
0      Patsy goes to New York Fashion Week to find id...   
1      Patsy goes to New York Fashion Week to find id...   
2      Patsy goes to New York Fashion Week to find id...   
3      The family set about clearing up after the dis...   
4      The family set about clearing up after the dis...   
...                                                  ...   
11073  A trip to Rotorua to search the archives revea...   
11074  Hitting dead ends and unable to contact key wi...   
11075  Hitting dead ends and unable to contact key wi...   
11076  The survivor of a disastrous circus event in t...   
11077  The survivor of a disastrous circus event in t...   

                                                   image  \
0      https://play-images-prod-catalog.tech.tvnz.co....   
1      https://play-images-prod-catalog.tech.tvnz.co....   
2      https://play-images-prod-catalog.tech.tvnz.co....   
3      https://play-images-prod-catalog.tech.tvnz.co....   
4      https://play-images-prod-catalog.tech.tvnz.co....   
...                                                  ...   
11073  https://play-images-prod-catalog.tech.tvnz.co....   
11074  https://play-images-prod-catalog.tech.tvnz.co....   
11075  https://play-images-prod-catalog.tech.tvnz.co....   
11076  https://play-images-prod-ctf.tech.tvnz.co.nz/a...   
11077  https://play-images-prod-ctf.tech.tvnz.co.nz/a...   

                                                     url  \
0      https://www.tvnz.co.nz/shows/absolutely-fabulo...   
1      https://www.tvnz.co.nz/shows/absolutely-fabulo...   
2      https://www.tvnz.co.nz/shows/absolutely-fabulo...   
3       https://www.tvnz.co.nz/shows/back/episodes/s1-e5   
4       https://www.tvnz.co.nz/shows/back/episodes/s1-e5   
...                                                  ...   
11073  https://www.tvnz.co.nz/shows/who-killed-lucy-t...   
11074  https://www.tvnz.co.nz/shows/who-killed-lucy-t...   
11075  https://www.tvnz.co.nz/shows/who-killed-lucy-t...   
11076  https://www.tvnz.co.nz/shows/who-killed-lucy-t...   
11077  https://www.tvnz.co.nz/shows/who-killed-lucy-t...   

                                                keywords    category   ID_x  \
0      genre:comedy,genre:box-set,genre:christmas,moo...      comedy      0   
1      genre:comedy,genre:box-set,genre:christmas,moo...      comedy      0   
2      genre:comedy,genre:box-set,genre:christmas,moo...      comedy      0   
3      genre:box-set,genre:comedy,mood:irreverent,moo...      comedy      6   
4      genre:box-set,genre:comedy,mood:irreverent,moo...      comedy      6   
...                                                  ...         ...    ...   
11073  genre:documentary,genre:new-zealand,genre:box-...  true-crime  16616   
11074  genre:documentary,genre:new-zealand,genre:box-...  true-crime  16618   
11075  genre:documentary,genre:new-zealand,genre:box-...  true-crime  16618   
11076  genre:documentary,genre:new-zealand,genre:box-...  true-crime  16622   
11077  genre:documentary,genre:new-zealand,genre:box-...  true-crime  16622   

       cluster  rating                                            comment  \
0            4       4  Answer find car he although hot bank. Somebody...   
1            4       3  Amount floor concern open act decision. 

In [89]:
# import numpy

# content = pd.read_csv('TVNZ_movies_v3.csv')

# k_means = content['k_means']

# rating_matrix = numpy.zeros(shape=(152,101))

# for j in range(101):
#     clusters = random.sample(set([0, 1, 2, 3, 4, 5, 6]), 2)
#     like = clusters[0]
#     dislike = clusters[1]
#     for movie in range(152):
#         if (k_means[movie] == like):
#             if (random.random() < 0.7):
#                 rating_matrix[movie][j] = random.randrange(1,6)
#                 #print("user ", j, "likes cluster ", like, "and rated movie ", movie, "with a ", rating_matrix[movie][j])
#         if (k_means[movie] == dislike):
#             if (random.random() < 0.7):
#                 rating_matrix[movie][j] = random.randrange(-5,0)
#                 #print("user ", j, "dislikes cluster ", dislike, "and rated movie ", movie, "with a ", rating_matrix[movie][j])

# print(rating_matrix)

[[ 0.  2.  0. ...  0.  0.  0.]
 [ 0.  3.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... -1.  0.  4.]
 [ 3.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]


C:\Users\SaltFarmer\AppData\Local\Temp\ipykernel_9480\2325347673.py:10: DeprecationWarning: Sampling from a set deprecated
since Python 3.9 and will be removed in a subsequent version.
  clusters = random.sample(set([0, 1, 2, 3, 4, 5, 6]), 2)


In [87]:
user_data['ID']

0        0
1        1
2        2
3        3
4        4
      ... 
96      96
97      97
98      98
99      99
100    100
Name: ID, Length: 101, dtype: int64

In [81]:
content['ID']

0        0
1        1
2        2
3        3
4        4
      ... 
147    147
148    148
149    149
150    150
151    151
Name: ID, Length: 152, dtype: int64

In [79]:
numpy.shape(rating_matrix)

(152, 100)

In [90]:
# pd.DataFrame(rating_matrix, index=content['ID'], columns=user_data['ID'])

ID   0    1    2    3    4    5    6    7    8    9    ...  91   92   93   \
ID                                                     ...                  
0    0.0  2.0  0.0  0.0  4.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1    0.0  3.0  0.0  0.0  3.0  0.0 -4.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2    0.0  0.0  0.0  0.0  4.0  0.0 -3.0  0.0  0.0  0.0  ...  0.0 -4.0  0.0   
3    0.0  0.0 -1.0  0.0 -1.0  2.0  0.0 -3.0  0.0  0.0  ...  0.0  0.0  0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
147  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
148  0.0  2.0  0.0  0.0  4.0  0.0 -4.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
149  0.0  0.0  0.0  0.0  0.0  0.0  0.0  5.0 -2.0  0.0  ...  0.0  0.0  0.0   
150  3.0  0.0  0.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0  ...  0.0  0.0 -3.0   
151  0.0  0.0  0.0  0.0  0.0  0.0 -3.0  0.0  0.0  0.0  ...  0.0 -2.0  0.0   

ID   94   95   96   97   98   99   100  
ID                                      
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4    5.0 -2.0  0.0  0.0  0.0  0.0  0.0  
..   ...  ...  ...  ...  ...  ...  ...  
147  0.0 -1.0  0.0  2.0  0.0  0.0  0.0  
148  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
149  0.0  0.0  0.0  0.0 -1.0  0.0  4.0  
150  0.0  0.0 -1.0  0.0  0.0  0.0  0.0  
151  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[152 rows x 101 columns]

In [16]:
combine.groupby('content_id').mean().sort_values(by=['rating'], ascending=False).head(5).index.values

TypeError: 'numpy.ndarray' object is not callable

# Nearest Neighbour

In [24]:
# df = rating_data.groupby(['user_id', 'content_id']).max('rating').reset_index()
df = rating_data.pivot(index='content_id', columns='user_id', values='rating').fillna(0)
df

user_id     0    1    2    3    4    5    6    7    8    9    ...  91   92   \
content_id                                                    ...             
0           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
6           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
7           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
13          0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
17          0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...         ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
16614       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 -4.0  0.0  ...  0.0  0.0   
16615       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
16616       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
16618       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
16622       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   

user_id     93   94   95   96   97   98   99   100  
content_id                                          
0           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
6           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
7           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
13         -3.0  0.0  2.0  0.0  0.0  0.0  0.0  0.0  
17          0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...         ...  ...  ...  ...  ...  ...  ...  ...  
16614       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
16615       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
16616       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
16618       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
16622       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5271 rows x 101 columns]

130

In [25]:
from sklearn.neighbors import NearestNeighbors

knn = NearestNeighbors(metric='cosine', algorithm='brute')

knn.fit(df.values)

distances, indices = knn.kneighbors(df.values, n_neighbors=len(df))

In [26]:
neighbours = {}

for i in range(0, len(indices)):
    nn = indices[i]
    dist = distances[i]    
    e = nn[0]
    e_content = df.index[e]    
    neighbours[e_content] = {"nn": [df.index[n] for n in nn[1:]], "dist": [1 - x for x in dist[1:]]}

In [29]:
indices

array([[   0, 2432, 4780, ...,  352, 3407, 4420],
       [   1, 4204, 5211, ..., 4866, 4873, 4875],
       [   2, 1081, 2949, ..., 4107, 4103, 4123],
       ...,
       [5268, 2204, 1637, ..., 1531, 3895, 5108],
       [5269, 2951, 1702, ..., 4110, 4105, 4140],
       [5270, 1770, 1751, ..., 2690, 2661, 2749]], dtype=int64)

In [124]:
recom4 = content[content['ID'].isin(indices[][1:])]
recom4

ID                                            title  \
67    67                              Pool Boy Nightmare    
72    72                                   Bury The Past    
88    88  I Am Somebody's Child: The Regina Louise Story    
149  149                                         Beaches    
151  151                                        Homesick    

                                           description  \
67   When Gale ends her brief affair with pool clea...   
72   When a women strikes out at her abusive husban...   
88   The real-life story of Regina Louise, an Afric...   
149  An update to a classic tear-jerker, we witness...   
151  An ambitious cellist is invited to represent G...   

                                                   tag  \
67   genre:drama/crime-thriller,genre:drama,genre:m...   
72   genre:movie,genre:drama,mood:dark,mood:suspens...   
88   genre:drama,genre:drama/strong-female-lead,gen...   
149  genre:movie,genre:drama,genre:closed-captions,...   
151  genre:drama,genre:drama/foreign-language-subti...   

                                                 image  \
67   https://play-images-prod-ctf.tech.tvnz.co.nz/a...   
72   https://play-images-prod-ctf.tech.tvnz.co.nz/a...   
88   https://play-images-prod-ctf.tech.tvnz.co.nz/a...   
149  https://play-images-prod-ctf.tech.tvnz.co.nz/a...   
151  https://play-images-prod-ctf.tech.tvnz.co.nz/a...   

                                                  path  \
67   /Users/xutingxuan/Desktop/MSc ADS/B3_Personali...   
72   /Users/xutingxuan/Desktop/MSc ADS/B3_Personali...   
88   /Users/xutingxuan/Desktop/MSc ADS/B3_Personali...   
149  /Users/xutingxuan/Desktop/MSc ADS/B3_Personali...   
151  /Users/xutingxuan/Desktop/MSc ADS/B3_Personali...   

                                                 genre  \
67                  crime-thriller, drama, movie, soap   
72                                        movie, drama   
88   drama, strong-female-lead, real-life-stories, ...   
149                      movie, drama, closed-captions   
151           drama, foreign-language-subtitled, movie   

                                         mood distributor branded-vod  \
67                     thrilling, suspenseful         a-e    lifetime   
72               dark, suspenseful, thrilling         a-e    lifetime   
88                                    diverse         a-e    lifetime   
149  all-the-feels, nostalgic, warm-and-fuzzy         a-e    lifetime   
151                  psychological, thrilling      rialto  filmstream   

     k_means  k_genre        GenreType Language  Local  
67         2        0         Thriller  English      0  
72         2        4          Mystery  English      0  
88         2        2  Real Life Story  English      0  
149        4        3          Romance  English      0  
151        3        1            Drama   German      0

In [105]:
def predict_rating(user_id, content_id, neighbours):
    
    if content_id not in neighbours:
        print("no data for content_id")
        
    neighbours = neighbours[content_id]
    
    nn = neighbours['nn']
    dist = neighbours['dist']
    
    numerator = 0
    denominator = 0
    
    for i in range(0, len(nn)):
        
        content_id = nn[i]
        user_rating = df.loc[content_id, user_id]
        
        if user_rating > 0:
            
            numerator += user_rating * dist[i]
            denominator += dist[i]
            
    if denominator > 0:
        
        return numerator / denominator
    
    else: 
        
        return 0

In [108]:
predict_rating('1', '2', 5)

TypeError: argument of type 'int' is not iterable